//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieReviewPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class reviews
    {
        public int Id { get; set; }
        public int user_id { get; set; }
        public int movie_id { get; set; }
        public string review { get; set; }
        public int rating { get; set; }
        public System.DateTime date { get; set; }
    
        public virtual movies movies { get; set; }
        public virtual users users { get; set; }

    }
}
